version: 2
jobs:
  build:
    docker:
      # Primary container image
      - image: circleci/node:10.14.2
      # Service container images
      - image: circleci/mongo:4.0.5
    steps:
      - checkout
      - run: echo "A first hello"
      - run: npm install
      - run: npm run configDB
      - run: sleep 3
      - run: pkill -npm
      - run: npm run seed
      - run: npm run start
      - run: npm run test
